---
id: use-error-boundary
title: useErrorBoundary
---

`useErrorBoundary` allows components to catch and handle errors higher up in the tree and provide appropriate fallback, logging or retry mechanisms.

A component becomes an error boundary when it declares a `useErrorBoundary` hook. The lambda passed to `useErrorBoundary` will receive any exceptions that are raised in rendering or dispatching events of components sitting underneath the error boundary in the tree.

`useErrorBoundary` can be used in combination with [`useState`](/mainconcepts/use-state.mdx), to update the state with the exception that was caught. This will then trigger a render pass with the new state value in order to replace the crashing component with an error message, or not display it at all.

## Example: Showing an Error State in UI

The code sample below shows how a component can gracefully handle an error in one of its child components and render an error state instead of crashing the app:

```kotlin file=sample/src/main/java/com/facebook/samples/litho/kotlin/errors/KErrorBoundary.kt start=start_example end=end_example
```

### Re-raising Errors

An error boundary may choose to only handle certain classes of errors. You can re-raise an exception from within the `useErrorBoundary` hook so that it propagates up the component tree until it is either caught by another error boundary or hits the root and causes a crash. This is done by calling [`ComponentUtils.raise`](pathname:///javadoc/com/facebook/litho/ComponentUtils.html#raise-com.facebook.litho.ComponentContext-java.lang.Exception-) with your context and the exception.

## Why not Try/Catch?

You may wonder why all this additional infrastructure would be necessary when you could just use try/catch. It turns out that there is no easily accessible place to wrap your Component code like this.

The following example shows how **not** to do it:

```kotlin file=sample/src/main/java/com/facebook/samples/litho/kotlin/errors/KIncorrectErrorHandlingComponent.kt start=start_example end=end_example
```

Assuming that PossiblyCrashingSubTitleComponent throws an exception in onCreateLayout this would not be caught by this block. The reason for this is that you are just returning a declaration of your layout here and don't actually execute any code. This is the responsibility of the Litho framework, hence the need to provide higher-level infrastructure to give you access to those errors.
